name: 🚀 Auto Release

on:
    push:
        branches: ["main"]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2
                  token: ${{ secrets.PAT_TOKEN }}

            - name: 🧐 Check if package.json version changed
              id: check_version
              run: |
                  OLD_VERSION=$(git show HEAD~1:package.json | jq -r .version)
                  NEW_VERSION=$(jq -r .version package.json)
                  echo "Old version: $OLD_VERSION"
                  echo "New version: $NEW_VERSION"

                  if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
                    echo "version_changed=true" >> $GITHUB_OUTPUT
                    echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
                  else
                    echo "version_changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: 🚀 Create GitHub Release
              if: steps.check_version.outputs.version_changed == 'true'
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.check_version.outputs.version }}
                  name: Release v${{ steps.check_version.outputs.version }}
                  body: |
                      🎉 Automatic release for version v${{ steps.check_version.outputs.version }}
                      Changes in this release:
                      - Version bump in package.json
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
