name: 🚀 Auto Release

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.PAT_TOKEN }}

      - name: 🧐 Check if package.json version changed
        id: check_version
        run: |
          OLD_VERSION=$(git show HEAD~1:package.json | jq -r .version)
          NEW_VERSION=$(jq -r .version package.json)
          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"

          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

            OLD_MAJOR=$(echo $OLD_VERSION | cut -d. -f1)
            OLD_MINOR=$(echo $OLD_VERSION | cut -d. -f2)
            OLD_PATCH=$(echo $OLD_VERSION | cut -d. -f3)

            NEW_MAJOR=$(echo $NEW_VERSION | cut -d. -f1)
            NEW_MINOR=$(echo $NEW_VERSION | cut -d. -f2)
            NEW_PATCH=$(echo $NEW_VERSION | cut -d. -f3)

            if [ "$NEW_MAJOR" -gt "$OLD_MAJOR" ]; then
              TYPE="Major"
            elif [ "$NEW_MINOR" -gt "$OLD_MINOR" ]; then
              TYPE="Minor"
            elif [ "$NEW_PATCH" -gt "$OLD_PATCH" ]; then
              TYPE="Patch"
            else
              TYPE="Unknown"
            fi

            echo "update_type=$TYPE" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: 🚀 Create GitHub Release
        if: steps.check_version.outputs.version_changed == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.check_version.outputs.version }}
          name: Release v${{ steps.check_version.outputs.version }}
          body: |
            🎉 Automatic release for version **v${{ steps.check_version.outputs.version }}**  
            🔖 Update type: **${{ steps.check_version.outputs.update_type }}**  

            📄 For full details, check the [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md)  
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
