name: 🍡 njsscan SARIF 🍩

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '0 22 * * *'

permissions:
  contents: read

jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: 🔍 Run njsscan
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🚨 Run nodejsscan
        uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
        with:
          args: >-
            . 
            --sarif 
            --output results.sarif

      - name: 📤 Upload njsscan SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
