name: "🍡 Sync README to Profiles 🍩"

on:
  push:
    branches:
      - main
    paths:
      - README.md

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "🍙 Checkout Liora repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "🍩 Clone Profile Repo (Naruya Izumi)"
        run: |
          git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/naruyaizumi/naruyaizumi.git profile-repo-izumi

      - name: "🍰 Copy README to Profile Repo (Naruya Izumi)"
        run: |
          cp README.md profile-repo-izumi/README.md

      - name: "🍬 Commit & Push to Profile Repo (Naruya Izumi)"
        run: |
          cd profile-repo-izumi
          git config user.name "🍡 Liora Bot"
          git config user.email "liora@bot"
          git add README.md || true
          git commit -m "🍰 Sync README from Liora Repo → Izumi" || echo "✨ No changes to commit"
          git push origin main

      - name: "🍩 Clone Profile Repo (Liora Official)"
        run: |
          git clone https://x-access-token:${{ secrets.PAT_LIORA }}@github.com/liora-official/liora-official.git profile-repo-liora

      - name: "🍰 Copy README to Profile Repo (Liora Official)"
        run: |
          cp README.md profile-repo-liora/README.md

      - name: "🍬 Commit & Push to Profile Repo (Liora Official)"
        run: |
          cd profile-repo-liora
          git config user.name "🍡 Liora Bot"
          git config user.email "liora@bot"
          git add README.md || true
          git commit -m "🍰 Sync README from Liora Repo → Liora Official" || echo "✨ No changes to commit"
          git push origin main
